
---
- name: setup testing of various variables from the inventory and group
  hosts: all
  gather_facts: false
  become: yes
  vars:
    my_cgroups:
      - name: "firewalld.service"
        properties:
          CPUShares: 975
      - name: "atomic-openshift-node.service"
        properties:
          CPUShares: 3036
          MemoryLimit: 8G

  roles:
    - systemctl
  tasks:
    - name: Test cgroups-module
      systemctl:
          name: sshd.service
          properties:
            CPUShares: 950
            MemoryLimit: 850M

    # - name: Set props from a list of objects
    #   systemctl:
    #     name: "{{ service_manage.name }}"
    #     properties: "{{ service_manage.properties }}"
    #   loop: "{{ my_cgroups }}"
    #   loop_control:
    #     loop_var: service_manage
      